name: neri veya Gelitirme Talebi
description: Yeni bir 繹zellik, gelitirme veya iyiletirme talebinde bulunun.
title: "[neri] <K覺sa a癟覺klama>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ##  Ne 繹nermek istiyorsunuz?
        Yeni bir 繹zellik, gelitirme veya iyiletirme fikrinizi aa覺da paylaabilirsiniz.

  - type: textarea
    id: description
    attributes:
      label: A癟覺klama
      description: Talebinizi detayland覺r覺n.
      placeholder: "nerinizi ayr覺nt覺l覺 olarak a癟覺klay覺n."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivasyon
      description: Bu gelitirme neden 繹nemli?
      placeholder: "renci, kul羹p veya platform i癟in salayaca覺 katk覺y覺 belirtin."
    validations:
      required: false

  - type: input
    id: related
    attributes:
      label: 襤lgili K覺s覺mlar
      description: Hangi k覺s覺mlar/ekranlar/繹zellikler etkilenebilir?
      placeholder: "繹r: Anasayfa, Etkinlikler, yelik"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Katk覺 Kurallar覺
      description: Katk覺 kurallar覺n覺 okudum ve kabul ediyorum.
      options:
        - label: Katk覺 kurallar覺n覺 okudum ve kabul ediyorum.
          required: true